### ISSUE TITLE
The platform does not remember the choice of user interface language (after logout and login).

### ISSUE THREAD

**Issue by komil-pro** [UstadMobile/UstadMobile#387]
When user sign out and sign in - the platform interface languages resets (not remembered). Save interface language setting in user profile or so.

**Comment by poojaustad** [comment]
https://tree.taiga.io/project/mikedawson-ustad-mobile/issue/67

**Comment by mikedawson** [comment]
I think this issue is obsolete. Language is remembered on each device. It is not tied to a user profile. The default language will be the default language of the mobile device / browser. The user can choose a different language, and that language will be saved. It will apply for all users on that browser / device.
