### ISSUE TITLE
Usability || Unintended Teacher Outcome "Failed" Option on New Enrollment Screen

### ISSUE THREAD

**Issue by poojaustad** [UstadMobile/UstadMobile#579]
**Describe the bug**

This bug report addresses an unintended issue on the "New Enrollment" screen, where an inappropriate option to set a teacher's outcome as "Failed" is present. This contradicts the expected behavior and purpose of teacher outcomes, leading to confusion and inaccuracies.

**Expected behavior**

On the "New Enrollment" screen, teacher outcomes should consist of options that accurately represent the intended evaluation of teachers' performance, excluding options like "Failed."

**Comment by poojaustad** [comment]
![Screenshot from 2023-08-18 22-45-26](https://github.com/UstadMobile/UstadMobile/assets/78338755/a6328982-933b-4851-bf22-9716cbd7f760)

**Comment by mikedawson** [comment]
This can be changed, but currently I don't think it is causing any significant issue for users.

**Comment by mikedawson** [comment]
The screen is now updated so that outcomes are not displayed if enrolling a teacher.

![Screenshot from 2023-12-05 13-30-13](https://github.com/UstadMobile/UstadMobile/assets/4280622/cc05820b-284a-4726-be6f-3247acbddf18)

![Screenshot from 2023-12-05 13-30-20](https://github.com/UstadMobile/UstadMobile/assets/4280622/5eebf15a-3d5a-4e5a-a0a1-f13760196586)
