### ISSUE TITLE
Crashes on clicking the text book  or the details of the module in a Course

### ISSUE THREAD

**Issue by mhdosman** [UstadMobile/UstadMobile#783]
**Describe the bug**
Crash happened on clicking the text book  or the details of the module in a Course
**To Reproduce**
1. Go to Courses and choose a course (Grade 5 Math for example)
2. Click on the course,
3. Click on the National Math textbook
4. It crashes

**Expected behavior**
to open the text book and browse it.

**Screenshots**

https://github.com/UstadMobile/UstadMobile/assets/153509442/a1794744-9b7a-4fbb-8a5b-3cbd06bcd5a7
**Smartphone (please complete the following information):**
 - Device: Samsung A53

**Comment by mikedawson** [comment]
Hi @mhdosman  - thank you for noting this. As per the [milestone](https://github.com/UstadMobile/UstadMobile/milestone/8) these screens aren't in the APK yet, hence the app crashes when you try to get to those screens. They are available on the web. This is being added shortly.

**Comment by mikedawson** [comment]
@mhdosman I think this issue is now resolved (screen recording below). Can you please confirm, and if resolved, close the issue. If there is anything else remaining on this issue, please add a comment.

[Screencast from 2024-01-18 13-13-41.webm](https://github.com/UstadMobile/UstadMobile/assets/4280622/49255190-7b8b-4078-a741-9478438dcfb7)

**Comment by mhdosman** [comment]
Fixed, thanks
