### ISSUE TITLE
Contrast Issue: Peer Grading Screen

### ISSUE THREAD

**Issue by mhdosman** [UstadMobile/UstadMobile#800]
**Describe the bug**
Contrast Issue: Peer Grading Screen

**To Reproduce**
1. Login as a teacher
2. Go to courses tab (Choose Test 17.01.2024)
3. Scroll down to Peer Grading Assignment
5. Move to Submission tab
6. Some texts are in a black color not clear to the user 

**Expected behavior**

**Screenshots**
![WhatsApp Image 2024-01-18 at 11 12 37_12ce0461](https://github.com/UstadMobile/UstadMobile/assets/153509442/5992fdd0-ad90-47bd-94d9-ec762da85b66)

Smartphone (please complete the following information):

Device: Samsung A53
OS: Android

**Comment by mikedawson** [comment]
I think this issue is resolved as per screenshot above. @mhdosman can you please check, and if resolved, close the issue? If there is anything else on this, please add a comment. 

![Screenshot from 2024-01-18 13-43-36](https://github.com/UstadMobile/UstadMobile/assets/4280622/e416b8a3-a103-4ec9-a4c7-412d2ffcf1a0)
