### ISSUE TITLE
Uploading and opening EPUB in desktop version (v.0.4.50)

### ISSUE THREAD

**Issue by komil-pro** [UstadMobile/UstadMobile#821]
**Describe the bug**
Getting error, when trying to upload EPUB and open existing EPUB file.

**Screenshots**

![uploading_epub_issue](https://github.com/UstadMobile/UstadMobile/assets/60223648/62645d98-e67e-4cdc-8c02-49a1aafa9f4a)

![opening_epub_issue](https://github.com/UstadMobile/UstadMobile/assets/60223648/341688d5-d012-488f-8636-5b5500c31e89)

**Desktop (please complete the following information):**
 - OS: Windows 10 x64
 - Version 0.4.50

**Comment by mikedawson** [comment]
@komil-pro  please attach the epub file you attempted to upload. It is saying that the file was invalid - which would be the case if the table of contents references a page that does not exist inside the epub.

**Comment by mikedawson** [comment]
Looking at the error message in the epub - I think I see what the problem might be. It seems like on Windows it is attempting to use '\' to find files within an epub, instead of using '/'. Still, please do upload a copy of the file.

**Comment by mikedawson** [comment]
This is fixed in version 0.4.59. It was caused by a path library using the Windows backslash. 

[Screencast from 2024-02-07 21-52-39.webm](https://github.com/UstadMobile/UstadMobile/assets/4280622/0eb372e2-eacf-43ad-af02-0299c7c5ff9c)

@komil-pro please check with version 0.4.59, and if fixed, please close the issue. If not fixed, please add a comment and let us know what problem remains.

**Comment by komil-pro** [comment]
Checked with version 0.4.64 - the issue has been resolved (with new uploaded files it is working fine, maybe there was some issue with old files, uploaded into the library).
