### ISSUE TITLE
In the course: downloading a file is not being finished

### ISSUE THREAD

**Issue by mhdosman** [UstadMobile/UstadMobile#824]
**Describe the bug**
Downloading a file is not being finished
**To Reproduce**
1. Go to Courses
2. Click on Unicef course
3. Scroll down to PDF Test file and click on it
4. Start downloading the file,
5. Wait and wait and the download seems to be complete but not change in the status of the button

**Expected behavior**
After finishing the download, the button has to be labeled  Remove

**Screenshots**
<img width="950" alt="image" src="https://github.com/UstadMobile/UstadMobile/assets/153509442/9d4764dd-7b52-46d2-b89b-e02aa757cf4e">

**Desktop (please complete the following information):**
 - OS:Win 11
 - Version : v0.4.51

**Comment by poojaustad** [comment]
Dear Muhammad,

The issue mentioned was not able to reproduce on our end, could you please try with the latest version of the app? If the issue is still reproduced, then please attach that content file too for testing. Thanks.

**Screenshots**
https://github.com/UstadMobile/UstadMobile/assets/78338755/fbe11f79-f52b-429e-bc53-bb027f80ddae

![2024-02-08_13h23_22](https://github.com/UstadMobile/UstadMobile/assets/78338755/f4e5e5d2-5954-40cf-99f2-5347d5339a2d)


**Desktop :**
OS:Win 11
Version : v0.4.59
