### ISSUE TITLE
Users under 13 can register using parental approval link

### ISSUE THREAD

**Issue by komil-pro** [UstadMobile/UstadMobile#832]
**Describe the bug**
Testing task 6.3
Users under 13 can register using parental approval link
This feature is not fully implemented. So email sending from platform, but rest functionality needs to be finalized.

**Expected behavior**
If user is under 13 y.o. parental approval required.

**Screenshots**

![Screenshot 2024-02-10 120310](https://github.com/UstadMobile/UstadMobile/assets/60223648/667eabf0-4d60-4769-819c-fee778c6981d)

![Screenshot 2024-02-10 120349](https://github.com/UstadMobile/UstadMobile/assets/60223648/ae2e4c7e-09e7-494c-b26c-b0458cac29fa)

![Screenshot 2024-02-10 120453](https://github.com/UstadMobile/UstadMobile/assets/60223648/a0269713-89d0-4929-a75a-940b10793890)

![Screenshot 2024-02-10 120533](https://github.com/UstadMobile/UstadMobile/assets/60223648/fdc32780-b6a3-479b-86b0-781ed1ac01c9)

![Screenshot 2024-02-10 120559](https://github.com/UstadMobile/UstadMobile/assets/60223648/a3cbeb5b-d1fd-4bd9-adbd-8ce1fecafb9c)

**Comment by mikedawson** [comment]
@komil-pro thank you for providing details. From the screen shots, it looks like you are trying to login as the child user after opening the link.

The child cannot approve their own registration. These screen shots seem to show the expected behavior.

To approve the registration:

1. You can login as an existing (adult) user to approve
2. If creation of new accounts is enabled, you can create a new account (where the date of birth shows that the user is above 18)

Maybe we should update the message to be clearer.

**Comment by komil-pro** [comment]
Checked by colleagues, it works.
