### ISSUE TITLE
Android app || The Assign reviewers text inside the button in assignment page is not correctly aligned

### ISSUE THREAD

**Issue by poojaustad** [UstadMobile/UstadMobile#886]
**Describe the bug**
The Assign Reviewers text inside the button on the assignment page is not correctly aligned

**To Reproduce**
1. Go to the Assignment edit page
2. Change marked as to Peers
3. The Assign Reviewers button appears which is not correctly aligned

**Expected behavior**
The Assign Reviewers button on the assignment page should be correctly aligned

**Screenshots**
![Screenshot from 2024-05-27 12-11-22](https://github.com/UstadMobile/UstadMobile/assets/78338755/c69dae60-82e6-47fb-9fbf-24181dd11fa3)

**Comment by mikedawson** [comment]
I think this is fixed with the above mentioned commit on the latest primary. @poojaustad please check. This is now adaptive, screenshots as below.

![Screenshot from 2024-07-15 21-09-34](https://github.com/user-attachments/assets/73bb238b-8cfe-4600-8903-a01288675a46)

![Screenshot from 2024-07-15 21-09-18](https://github.com/user-attachments/assets/76d11c3b-14f9-49bc-b0c0-45c3b1f71a54)

**Comment by poojaustad** [comment]
Tested, this issue has been fixed.
