### ISSUE TITLE
Bug Report of VSO School App

### ISSUE THREAD

**Issue by aakabir** [UstadMobile/UstadMobile#99]
VSOSchool 1.1: Though internet is connect but sometimes it shows that no internet.
VSOSchool 1.2: Max file size is 213 MB but while download it, it goes above 213 MB.
VSOSchool 1.3: While transfer in peer to peer, the receiver has this type of notification.
VSOSchool 1.4: But in sender's end it already transferring. the file is transfer max 34%.
VSOSchool 1.5: The panel is looks like this.

The referral value  used "VSOSchool 1.00" is the rename of screenshot.
Others problem: 
1.While peer to peer data transfer broken then all the content is not shown in senders end.
2. While i go deep in folder from root folder (like: New folder>New folder 1>New Folder 2) if press back button, it takes in root folder (like: New Folder 2<New Folder) but it should be like (New Folder 2<New Folder 1<New Folder)

![VSOSchool 1 (1)](https://user-images.githubusercontent.com/33418194/76378956-025c0880-6379-11ea-8b34-df44f0e4f03c.jpeg)
![VSOSchool 1 (2)](https://user-images.githubusercontent.com/33418194/76378958-0425cc00-6379-11ea-82ff-d8d99b9bc2a6.jpeg)
![VSOSchool 1 (3)](https://user-images.githubusercontent.com/33418194/76378959-04be6280-6379-11ea-802d-270799394ce1.jpeg)
![VSOSchool 1 (4)](https://user-images.githubusercontent.com/33418194/76378961-0556f900-6379-11ea-9f9d-d593a567b884.jpeg)
![VSOSchool 1 (5)](https://user-images.githubusercontent.com/33418194/76378962-05ef8f80-6379-11ea-8bfe-76322a26537a.jpeg)

**Comment by mikedawson** [comment]
Hi @aakabir  - thank you for your report on this version of the app. I think there are really three issues here which are part of the app. Can you please post one issue GitHub per issue in the app, so that we can track fixing it accordingly?

E.g. 1.1 "Download dialog shows no connection although Internet is connected"
1.2 "Download progress shows above size of file"
1.3 -1.4 I'm afraid this is not really part of the Ustad app. This is the built-in bluetooth file sharing that is part of Android. It might be if you are using an older version of Android, and/or there is a lot of WiFi or bluetooth activity in the area that this is slow or unreliable. You might need to consider sharing the APK using a memory card or something like that instead in that case.
1.5 "Download panel buttons are not showing correctly"

Thanks!

**Comment by aakabir** [comment]
Thanks Mike for your quick response. Ill open individual ticket for each issue. 1.3 -1.4 we will try it by memory card. See you in the meeting.
